import { Injectable } from '@angular/core';

import { car } from './car';
@Injectable({
  providedIn: 'root'
})
export class CarServiceService {

  constructor() { }
searsh="";
  carList:car[]=[
    {
      id: 1,
      name: 'Luxury Sedan X1',
      price:3000,
      prductionDate: '2022-01-01',
      fule: 'Petrol',
      mileage: 10000,
      image1: '../../../../assets/car images/img1.webp',
      image2: '../../../../assets/car images/img1.webp',
      image3: '../../../../assets/car images/img1.webp',

      rentedNow:false,
      power:164,
      gearbox:"Manual",
      bodyType:"Coupe",
      type:"Used",
      drivetrain:"Front",
      seats:4,
      doors:2
    },
    {
      id: 2,
      name: 'Sporty Coupe S3',
      price:2500,
      prductionDate: '2021-08-15',
      fule: 'Diesel',
      mileage: 15000,
      image1: '../../../../assets/car images/img2.webp',
      image2: '../../../../assets/car images/img2.webp',
      image3: '../../../../assets/car images/img2.webp',
      rentedNow:false,
      power:164,
      gearbox:"Manual",
      bodyType:"Coupe",
      type:"Used",
      drivetrain:"Front",
      seats:4,
      doors:2
    },
    {
      id: 3,
      name: 'Electric City Car E5',
      price:1500,
      prductionDate: '2022-03-20',
      fule: 'Electric',
      mileage: 5000,
      image1: '../../../../assets/car images/img3.webp',
      image2: '../../../../assets/car images/img3.webp',
      image3: '../../../../assets/car images/img3.webp',
      rentedNow:false,
      power:164,
      gearbox:"Manual",
      bodyType:"Coupe",
      type:"Used",
      drivetrain:"Front",
      seats:4,
      doors:2
    },
   
    {
      id: 4,
      name: 'Family SUV Q7',
      price:1200,
      prductionDate: '2022-06-10',
      fule: 'Hybrid',
      mileage: 12000,
      image1: '../../../../assets/car images/img4.webp',
      image2: '../../../../assets/car images/img4.webp',
      image3: '../../../../assets/car images/img4.webp',
      rentedNow:false,
      power:164,
      gearbox:"Manual",
      bodyType:"Coupe",
      type:"Used",
      drivetrain:"Front",
      seats:4,
      doors:2
    },
    {
      id: 5,
      name: 'Luxury Sedan X1',
      price:1400,
      prductionDate: '2022-01-01',
      fule: 'Petrol',
      mileage: 10000,
      image1: '../../../../assets/car images/img5.webp',
      image2: '../../../../assets/car images/img5.webp',
      image3: '../../../../assets/car images/img5.webp',
      rentedNow:false,
      power:164,
      gearbox:"Manual",
      bodyType:"Coupe",
      type:"Used",
      drivetrain:"Front",
      seats:4,
      doors:2
    },
    {
      id: 6,
      name: 'Sporty Coupe S3',
      price:1800,
      prductionDate: '2021-08-15',
      fule: 'Diesel',
      mileage: 15000,
      image1: '../../../../assets/car images/img6.webp',
      image2: '../../../../assets/car images/img6.webp',
      image3: '../../../../assets/car images/img6.webp',
      rentedNow:true
      ,
      power:164,
      gearbox:"Manual",
      bodyType:"Coupe",
      type:"Used",
      drivetrain:"Front",
      seats:4,
      doors:2
      },
    {
      id: 7,
      name: 'Electric City Car E5',
      price:1400,
      prductionDate: '2022-03-20',
      fule: 'Electric',
      mileage: 5000,
      image1: '../../../../assets/car images/img7.webp',
      image2: '../../../../assets/car images/img7.webp',
      image3: '../../../../assets/car images/img7.webp',
      rentedNow:false,
      power:164,
      gearbox:"Manual",
      bodyType:"Coupe",
      type:"Used",
      drivetrain:"Front",
      seats:4,
      doors:2
    },
  
    {
      id: 8,
      name: 'Family SUV Q7',
      price:2000,
      prductionDate: '2022-06-10',
      fule: 'Hybrid',
      mileage: 12000,
      image1: '../../../../assets/car images/img8.webp',
      image2: '../../../../assets/car images/img8.webp',
      image3: '../../../../assets/car images/img8.webp',
      rentedNow:false,
      power:164,
      gearbox:"Manual",
      bodyType:"Coupe",
      type:"Used",
      drivetrain:"Front",
      seats:4,
      doors:2
    },
    {
      id: 9,
      name: 'Mercedes-Bens GlC',
      price:3000,
      prductionDate: '2022-01-01',
      fule: 'Petrol',
      mileage: 10000,
      image1: '../../../../assets/car images/img9.webp',
      image2: '../../../../assets/car images/img9.webp',
      image3: '../../../../assets/car images/img9.3.webp',
      rentedNow:false,
      power:164,
      gearbox:"Manual",
      bodyType:"Coupe",
      type:"Used",
      drivetrain:"Front",
      seats:4,
      doors:2
    },
    {
      id: 10,
      name: 'BMW 640',
      price:1400,
      prductionDate: '2021-08-15',
      fule: 'Diesel',
      mileage: 15000,
      image1: '../../../../assets/car images/img10.webp',
      image2: '../../../../assets/car images/img10.webp',
      image3: '../../../../assets/car images/img10.webp',
      rentedNow:true
      ,
      power:164,
      gearbox:"Manual",
      bodyType:"Coupe",
      type:"Used",
      drivetrain:"Front",
      seats:4,
      doors:2
     },
    {
      id: 11,
      name: 'Electric City Car E5',
      price:2500,
      prductionDate: '2022-03-20',
      fule: 'Electric',
      mileage: 5000,
      image1: '../../../../assets/car images/img11.webp',
      image2: '../../../../assets/car images/img11.webp',
      image3: '../../../../assets/car images/img11.webp',
      rentedNow:false,
      power:164,
      gearbox:"Manual",
      bodyType:"Coupe",
      type:"Used",
      drivetrain:"Front",
      seats:4,
      doors:2
    },
    
    {
      id: 12,
      name: 'Volkswagen Golf',
      price:1200,
      prductionDate: '2022-06-10',
      fule: 'Hybrid',
      mileage: 12000,
      image1: '../../../../assets/car images/img5.webp',
      image2: '../../../../assets/car images/img5.webp',
      image3: '../../../../assets/car images/img5.webp',
      rentedNow:true
      ,
      power:164,
      gearbox:"Manual",
      bodyType:"Coupe",
      type:"Used",
      drivetrain:"Front",
      seats:4,
      doors:2
     },
     {
      id: 13,
      name: 'Volkswagen Golf',
      price:1200,
      prductionDate: '2022-06-10',
      fule: 'Hybrid',
      mileage: 12000,
      image1: '../../../../assets/car images/img5.webp',
      image2: '../../../../assets/car images/img5.webp',
      image3: '../../../../assets/car images/img5.webp',
      rentedNow:true
      ,
      power:164,
      gearbox:"Manual",
      bodyType:"Coupe",
      type:"Used",
      drivetrain:"Front",
      seats:4,
      doors:2
     },
  ];

  indexOfCar=0;
  getIndex(index:number){
    this.indexOfCar=index-1;
  }
 
}
